require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PageTitlesController do

  # This should return the minimal set of attributes required to create a valid
  # PageTitle. As you add validations to PageTitle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PageTitlesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all page_titles as @page_titles" do
      page_title = PageTitle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:page_titles).should eq([page_title])
    end
  end

  describe "GET show" do
    it "assigns the requested page_title as @page_title" do
      page_title = PageTitle.create! valid_attributes
      get :show, {:id => page_title.to_param}, valid_session
      assigns(:page_title).should eq(page_title)
    end
  end

  describe "GET new" do
    it "assigns a new page_title as @page_title" do
      get :new, {}, valid_session
      assigns(:page_title).should be_a_new(PageTitle)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_title as @page_title" do
      page_title = PageTitle.create! valid_attributes
      get :edit, {:id => page_title.to_param}, valid_session
      assigns(:page_title).should eq(page_title)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PageTitle" do
        expect {
          post :create, {:page_title => valid_attributes}, valid_session
        }.to change(PageTitle, :count).by(1)
      end

      it "assigns a newly created page_title as @page_title" do
        post :create, {:page_title => valid_attributes}, valid_session
        assigns(:page_title).should be_a(PageTitle)
        assigns(:page_title).should be_persisted
      end

      it "redirects to the created page_title" do
        post :create, {:page_title => valid_attributes}, valid_session
        response.should redirect_to(PageTitle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_title as @page_title" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageTitle.any_instance.stub(:save).and_return(false)
        post :create, {:page_title => { "title" => "invalid value" }}, valid_session
        assigns(:page_title).should be_a_new(PageTitle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageTitle.any_instance.stub(:save).and_return(false)
        post :create, {:page_title => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_title" do
        page_title = PageTitle.create! valid_attributes
        # Assuming there are no other page_titles in the database, this
        # specifies that the PageTitle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PageTitle.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => page_title.to_param, :page_title => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested page_title as @page_title" do
        page_title = PageTitle.create! valid_attributes
        put :update, {:id => page_title.to_param, :page_title => valid_attributes}, valid_session
        assigns(:page_title).should eq(page_title)
      end

      it "redirects to the page_title" do
        page_title = PageTitle.create! valid_attributes
        put :update, {:id => page_title.to_param, :page_title => valid_attributes}, valid_session
        response.should redirect_to(page_title)
      end
    end

    describe "with invalid params" do
      it "assigns the page_title as @page_title" do
        page_title = PageTitle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageTitle.any_instance.stub(:save).and_return(false)
        put :update, {:id => page_title.to_param, :page_title => { "title" => "invalid value" }}, valid_session
        assigns(:page_title).should eq(page_title)
      end

      it "re-renders the 'edit' template" do
        page_title = PageTitle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageTitle.any_instance.stub(:save).and_return(false)
        put :update, {:id => page_title.to_param, :page_title => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_title" do
      page_title = PageTitle.create! valid_attributes
      expect {
        delete :destroy, {:id => page_title.to_param}, valid_session
      }.to change(PageTitle, :count).by(-1)
    end

    it "redirects to the page_titles list" do
      page_title = PageTitle.create! valid_attributes
      delete :destroy, {:id => page_title.to_param}, valid_session
      response.should redirect_to(page_titles_url)
    end
  end

end
