require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PageItemsController do

  # This should return the minimal set of attributes required to create a valid
  # PageItem. As you add validations to PageItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "position" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PageItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all page_items as @page_items" do
      page_item = PageItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:page_items).should eq([page_item])
    end
  end

  describe "GET show" do
    it "assigns the requested page_item as @page_item" do
      page_item = PageItem.create! valid_attributes
      get :show, {:id => page_item.to_param}, valid_session
      assigns(:page_item).should eq(page_item)
    end
  end

  describe "GET new" do
    it "assigns a new page_item as @page_item" do
      get :new, {}, valid_session
      assigns(:page_item).should be_a_new(PageItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested page_item as @page_item" do
      page_item = PageItem.create! valid_attributes
      get :edit, {:id => page_item.to_param}, valid_session
      assigns(:page_item).should eq(page_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PageItem" do
        expect {
          post :create, {:page_item => valid_attributes}, valid_session
        }.to change(PageItem, :count).by(1)
      end

      it "assigns a newly created page_item as @page_item" do
        post :create, {:page_item => valid_attributes}, valid_session
        assigns(:page_item).should be_a(PageItem)
        assigns(:page_item).should be_persisted
      end

      it "redirects to the created page_item" do
        post :create, {:page_item => valid_attributes}, valid_session
        response.should redirect_to(PageItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved page_item as @page_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageItem.any_instance.stub(:save).and_return(false)
        post :create, {:page_item => { "position" => "invalid value" }}, valid_session
        assigns(:page_item).should be_a_new(PageItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PageItem.any_instance.stub(:save).and_return(false)
        post :create, {:page_item => { "position" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested page_item" do
        page_item = PageItem.create! valid_attributes
        # Assuming there are no other page_items in the database, this
        # specifies that the PageItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PageItem.any_instance.should_receive(:update).with({ "position" => "1" })
        put :update, {:id => page_item.to_param, :page_item => { "position" => "1" }}, valid_session
      end

      it "assigns the requested page_item as @page_item" do
        page_item = PageItem.create! valid_attributes
        put :update, {:id => page_item.to_param, :page_item => valid_attributes}, valid_session
        assigns(:page_item).should eq(page_item)
      end

      it "redirects to the page_item" do
        page_item = PageItem.create! valid_attributes
        put :update, {:id => page_item.to_param, :page_item => valid_attributes}, valid_session
        response.should redirect_to(page_item)
      end
    end

    describe "with invalid params" do
      it "assigns the page_item as @page_item" do
        page_item = PageItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => page_item.to_param, :page_item => { "position" => "invalid value" }}, valid_session
        assigns(:page_item).should eq(page_item)
      end

      it "re-renders the 'edit' template" do
        page_item = PageItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PageItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => page_item.to_param, :page_item => { "position" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested page_item" do
      page_item = PageItem.create! valid_attributes
      expect {
        delete :destroy, {:id => page_item.to_param}, valid_session
      }.to change(PageItem, :count).by(-1)
    end

    it "redirects to the page_items list" do
      page_item = PageItem.create! valid_attributes
      delete :destroy, {:id => page_item.to_param}, valid_session
      response.should redirect_to(page_items_url)
    end
  end

end
